trigger: 
  - main
  - develop
  - release/*

# Don't trigger for a pull request
pr: none

# Include shared variables
variables:
- template: shared-variables.yml

stages:

- stage: Tagging

  jobs:
  - job: Tagging
  
    pool:
      vmImage: $(linuxImage)
     
    steps:
    - checkout: self
      submodules: recursive
      persistCredentials: true
    
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: 'Determine Version Number'
      # Give this task a name so we can use the variables it sets later.
      name: GitVersion
      inputs:
        preferBundledVersion: false
        configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'
    
    # Add a tag to the git repository with the version number.
    - task: ATP.ATP-GitTag.GitTag.GitTag@5
      displayName: 'Tag Repo With Version Number'
      inputs:
        tagUser: 'Azure DevOps'
        tagEmail: 'CIUser@51Degrees.com'
