parameters:
- name: imageName # Name of the image to run the job on

jobs:
# Determine the version of the current commit.
- template: shared-git-version-job.yml
  parameters:
    imageName: ${{ parameters.imageName }}
    
# Tag using the version from the gitversion job
- template: shared-git-tag-job.yml
  parameters:
    imageName: ${{ parameters.imageName }}
    jobDependencies: [Versioning]
