parameters:
- name: stageDependencies
  type: object
  default: []
- name: commonCiRef # The common-ci repo reference to checkout.
  type: string
  default: main
- name: project # The DevOps project executing this template.
  displayName: 'Calling project is cloud or non-cloud'
  type: string
  default: 'non-cloud'

stages:
# This stage check if current branch runs on a pull request merge branch,
# then try to complete the pull request if it is true.
# WARNINGS: This stage should be run at the end of a pipeline, because upon
# completing a pull request the pipeline will be canceled and no stage
# or tasks will be run after this.
- stage: Complete_PR
  displayName: "Check and complete corresponding pull request"
  dependsOn: ${{ parameters.stageDependencies }}

  variables:
  - group: CIAutomation # Required to access CI variables

  pool:
    vmImage: 'windows-2019'
    
  jobs:
  - job: Complete_PR
    
    steps:
    - checkout: self
      submodules: recursive
      persistCredentials: true

      # Checkout the common-ci to access the latest release configuration.
      # Special consideration is given to the cloud project as when executing 
      # this template the git url would resolve to git://Cloud/common-ci
      # which is not valid.
    - ${{ if eq(parameters.project, 'cloud') }}:
      - checkout: 'git://Pipeline/common-ci@${{ parameters.commonCiRef }}'
    - ${{ if ne(parameters.project, 'cloud') }}:
      - checkout: 'git://$(System.TeamProject)/common-ci@${{ parameters.commonCiRef }}'
      
    - powershell: |
        # Install all modules
        $Env:PSModulePath += ";$($(Get-Location).Path)\common-ci\scripts\modules"
        Write-Host "Module Path: $($Env:PsModulePath)"
        
        # Complete the corresponding pull request
        cd $Env:BUILD_REPOSITORY_NAME
        Write-Host "# Try to complete pull request for repository $Env:BUILD_REPOSITORY_NAME."
        if (!$(Complete-CorrespondingPullRequest -ConfigFile "$($(Get-Location).Path)\..\common-ci\release-config.json")) {
            Write-Host "# FAILED"
            exit 1
        }
      displayName: 'Complete Pull Request'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      condition: and(succeeded(), eq(variables['AutomatedRelease'], 'On'))