parameters:
- name: imageName # Name of the image to run the job on

jobs:
- job: Tagging

  variables:
  # Access token for the git repository. Used by the git tag task.
  - name: system_accesstoken
    value: $(System.AccessToken)
  
  pool:
    vmImage: ${{ parameters.imageName }}
  
  steps:
  # The lines below are needed to allow the pipeline access to the
  # OAuth access token that controls write access to the git repository.
  # (Required for GitTag task)
  - checkout: self
    persistCredentials: true
  
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: 'Determine Version Number'
    # Give this task a name so we can use the variables it sets later.
    name: GitVersion
    inputs:
      preferBundledVersion: false
  
  # Add a tag to the git repository with the version number.
  - task: ATP.ATP-GitTag.GitTag.GitTag@5
    displayName: 'Tag Repo With Version Number'
    inputs:
      tagUser: 'Azure DevOps'
      tagEmail: 'CIUser@51Degrees.com'
