parameters:
- name: imageName # Name of the image to run the job on
- name: commonCiRef # The common-ci repo reference to checkout.
  type: string
  default: main
- name: project # The DevOps project executing this template.
  displayName: 'Calling project is cloud or non-cloud'
  type: string
  default: 'non-cloud'

jobs:
# Determine the version of the current commit.
- template: shared-git-version-job.yml
  parameters:
    imageName: ${{ parameters.imageName }}
    commonCiRef: ${{ parameters.commonCiRef }}
    project: ${{ parameters.project }}
    
# Tag using the version from the gitversion job
- template: shared-git-tag-job.yml
  parameters:
    imageName: ${{ parameters.imageName }}
    jobDependencies: [Versioning]
