name: Inject secrets
inputs:
  files:
    type: string
    required: true
  secrets: # key-value json string
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - id: inject
      shell: pwsh
      env:
        files: ${{ inputs.files }}
        secrets: ${{ inputs.secrets }}
      run: |
        $ErrorActionPreference = "Stop"
        Set-StrictMode -Version 3.0
        $secrets = $env:secrets | ConvertFrom-Json -AsHashtable
        Get-ChildItem $env:files.Split("`n", [StringSplitOptions]::RemoveEmptyEntries) | ForEach-Object {
            $src = $_
            $dest = $src -clike '*.tpl' ? $src -replace '.tpl$' : $src # strip suffix from templates
            Write-Host "Injecting secrets into $dest"
            $json = $dest -clike '*.json'
            (Get-Content -Raw $src) -replace '%\w+%', {
                $name = $_.ToString().Trim('%')
                return $json ? ($secrets.$name | ConvertTo-Json).Trim('"') : $secrets.$name
            } | Set-Content $dest
        }
