parameters:
- name: imageName # Name of build image
- name: dependencies # Stages that this stage depends on
  type: object
  default: []

stages:
- stage: 'SecurityCheck'
  displayName: 'Security Vulnerability Check'
  dependsOn: ${{ parameters.dependencies }}
  
  jobs:
  - job: 'SecurityCheck'
    displayName: 'Security Vulnerability Check'
  
    pool:
      vmImage: ${{ parameters.imageName }}

    steps:
    - checkout: self
      submodules: recursive
      lfs: true
      persistCredentials: true

    # Perform a security vulnerability check on the dependencies
    # using dependency-check-maven plugin
    - bash: |
        mvn dependency-check:aggregate -Pdependency-check
      displayName: 'Maven dependency check'

    # Copy report to staging directory to be published
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: 'target/dependency-check-report.html'
        TargetFolder: '$(build.artifactstagingdirectory)'

    # Publish dependency check report
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: dependency-check-report'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: dependency-check-report