name: Publish Test Results
inputs:
  repo-name:
    type: string
    required: true
  name:
    type: string
    default: Test Results
  commit:
    type: string
    default: ${{ github.sha }}
  skip-unit:
    type: boolean
    default: false
  skip-integration:
    type: boolean
    default: false
  skip-performance:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # Unit
    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/unit/**/*.xml

    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/unit/**/*.xml

    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/unit/**/*.xml

    # Integration
    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/integration/**/*.xml

    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/integration/**/*.xml

    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/integration/**/*.xml

    # Performance
    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/performance/**/*.xml

    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/performance/**/*.xml

    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        files: common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
