name: Publish Test Results
inputs:
  repo-name:
    type: string
    required: true
  name:
    type: string
    default: Test Results
  commit:
    type: string
    default: ${{ github.sha }}
  skip-unit:
    type: boolean
    default: false
  skip-integration:
    type: boolean
    default: false
  skip-performance:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # Install compatible Python for macOS
    - name: Install Python 3.12
      if: ${{ runner.os == 'macOS' }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    # Unit
    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
          common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
          common/${{ inputs.repo-name }}/test-results/unit/**/*.json

    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
          common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
          common/${{ inputs.repo-name }}/test-results/unit/**/*.json

    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-unit == 'false' }}
      with:
        check_name: Unit Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
          common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
          common/${{ inputs.repo-name }}/test-results/unit/**/*.json

    # Integration
    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
          common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
          common/${{ inputs.repo-name }}/test-results/integration/**/*.json

    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
          common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
          common/${{ inputs.repo-name }}/test-results/integration/**/*.json

    - name: Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-integration == 'false' }}
      with:
        check_name: Integration Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
          common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
          common/${{ inputs.repo-name }}/test-results/integration/**/*.json

    # Performance
    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: ${{ runner.os == 'Linux' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
          common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
          common/${{ inputs.repo-name }}/test-results/performance/**/*.json

    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: ${{ runner.os == 'Windows' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
          common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
          common/${{ inputs.repo-name }}/test-results/performance/**/*.json

    - name: Performance Test Results
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: ${{ runner.os == 'macOS' && inputs.skip-performance == 'false' }}
      with:
        check_name: Performance Tests - ${{ inputs.name }}
        commit: ${{ inputs.commit }}
        action_fail: true
        files: |
          common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
          common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
          common/${{ inputs.repo-name }}/test-results/performance/**/*.json
