name: Compare performance
inputs:
  metrics:
    required: true
  save:
    default: false
  branch:
    default: performance-results
runs:
  using: "composite"
  steps:
    - shell: pwsh
      env:
        metrics: ${{ inputs.metrics }}
        save: ${{ inputs.save }}
        branch: ${{ inputs.branch }}
      run: . '${{ github.action_path }}/compare-performance.ps1'

