<#
.SYNOPSIS
    Download the shared web-example assets (CSS + JS) from the documentation
    pattern library into a consuming examples repository.

.DESCRIPTION
    The 51Degrees SDK web examples share a single look and feel generated by the
    pattern library in the documentation repo (the examples-main target). The
    built assets are published as GitHub Release assets tagged examples-assets-v*.

    This script downloads a pinned release into the consuming repo so the files
    are committed and visible to anyone cloning it. The assets change rarely, so
    re-running this only when a new release is cut keeps each repo in sync.

    This is the download primitive. The built assets are committed into each
    examples repo so anyone cloning it sees them; common-ci refreshes them in CI
    via the nightly-example-assets-update reusable workflow when a new release is
    cut (no submodule in the examples repos). It is also handy for the initial
    vendoring, e.g.:
        pwsh scripts/update-example-assets.ps1 -OutputDir path/to/wwwroot/assets

.PARAMETER OutputDir
    Directory (created if missing) the assets are written to.

.PARAMETER Tag
    Release tag to pull. Defaults to the current pinned version.

.PARAMETER Assets
    Asset file names to download.

.PARAMETER Repo
    owner/name of the repo hosting the release.
#>
param(
    [Parameter(Mandatory = $true)][string]$OutputDir,
    [string]$Tag = "examples-assets-v1.0.0",
    [string[]]$Assets = @(
        "examples-main.min.css",
        "examples-main.css",
        "examples.min.js",
        "examples.js"
    ),
    [string]$Repo = "51Degrees/documentation"
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

foreach ($asset in $Assets) {
    $url = "https://github.com/$Repo/releases/download/$Tag/$asset"
    $dest = Join-Path $OutputDir $asset
    Write-Host "Downloading $url"
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    if (-not (Test-Path $dest) -or (Get-Item $dest).Length -eq 0) {
        throw "Failed to download $asset from $url (empty or missing)."
    }
    Write-Host "  wrote $dest ($((Get-Item $dest).Length) bytes)"
}

Write-Host "Done. $($Assets.Count) asset(s) updated in $OutputDir from $Repo@$Tag."
