name: Install runtime
inputs:
  language:
    type: string
    required: true
  version:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Python
      if: inputs.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}
    - name: Install Node
      if: inputs.language == 'node'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
    - name: Install PHP
      if: inputs.language == 'php'
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.version }}
        tools: phpunit:9.6.22
    - name: Install Go
      if: inputs.language == 'go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.version }}
    - name: Install Dotnet
      if: inputs.language == 'dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.version }}

    # Used as a cross-compiler for C/C++ to target older glibc versions
    - name: Install Zig
      if: inputs.language == 'zig'
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ inputs.version }}
