name: Nightly Package Update

on:
  workflow_call:
    inputs:
        repo-name:
          required: true
          type: string
    secrets:
      token:
        required: true

jobs:
  nightly-package-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Checkout reusable workflow dir
        uses: actions/checkout@v3
        with:
          repository: 51degrees/common-ci
          path: common
        
      - name: Update Packages
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/nightly-package-update.ps1 `
          -GitHubToken ${{ secrets.token }} `
          -RepoName ${{ inputs.repo-name }} `
          -RunId ${{ github.run_id }}
