name: Nightly Data File Change

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      org-name:
        required: false
        type: string
        default: 51degrees
      user: # required for authenticating to a private nuget repo in tools' setup-environment.ps1
        required: false
        type: string
        default: Automation51D
      email:
        required: false
        type: string
        default: "51DCI@51Degrees.com"
      data-type:
        required: false
        type: string
        default: "HashV41"
      data-product:
        required: false
        type: string
        default: "V4TAC"
      data-filename:
        required: false
        type: string
        default: "TAC-HashV41.hash.gz"
      dryrun:
        required: false
        type: string
        default: false
      common-ci-ref:
        type: string
        default: ''
    secrets:
      token:
        required: true
      data-key:
        required: true
      data-url:
        required: false
        
jobs:
  nightly-data-file-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Checkout reusable workflow dir
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common
          ref: ${{ inputs.common-ci-ref }}
        
      - name: Generate Accessors
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $DryRun = [bool]::Parse( "${{ inputs.dryrun }}" )
          . ${{ github.workspace }}/common/nightly-data-file-change.ps1 `
          -GitHubToken ${{ secrets.token }} `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -Branch ${{ github.ref_name }} `
          -DataKey ${{ secrets.data-key }} `
          -DataUrl "${{ secrets.data-url }}" `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -DataType ${{ inputs.data-type }} `
          -Product ${{ inputs.data-product }} `
          -FileName ${{ inputs.data-filename }} `
          -DryRun $DryRun
