name: Nightly Documentation Update

on:
  workflow_call:
    inputs:
        repo-name:
          required: true
          type: string
    secrets:
      token:
        required: true
      device-detection-key:
        required: true
      device-detection-url:
        required: false
        
env:
  GITHUB_TOKEN: ${{ secrets.token }}

jobs:
  nightly-documentation-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Checkout reusable workflow dir
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          path: common
        
      - name: Generate Documentation
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/nightly-documentation-update.ps1 `
          -GitHubToken ${{ secrets.token }} `
          -RepoName ${{ inputs.repo-name }}
