name: Nightly PRs to Main

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      org-name:
        required: false
        type: string
        default: 51degrees
      user:
        required: false
        type: string
        default: Automation51D
      email:
        required: false
        type: string
        default: "51DCI@51Degrees.com"
      dryrun:
        required: false
        type: string
        default: false
      cache-assets:
        default: false
        type: boolean
      common-ci-ref:
        required: false
        type: string
        default: ''
      prs: # Comma-separated list of pull request IDs to build
        required: false
        type: string
    secrets:
      token:
        required: true
      AcceptCHBrowserKey:
      AcceptCHHardwareKey:
      AcceptCHNoneKey:
      AcceptCHPlatformKey:
      ApiKey:
      CsvUrl:
      DeviceDetection:
      DeviceDetectionUrl:
      JavaGpgKeyPassphrase:
      JavaPGP:
      MavenSettings:
      NPMAuthToken:
      NginxCert:
      NginxKey:
      PypiToken:
      TestBrowserResourceKey:
      TestHardwareResourceKey:
      TestLicenseKey:
      TestNoSetHeaderResourceKey:
      TestPlatformResourceKey:
      TestPypiToken:
      TestResourceKey:
      TestSuperResourceKey:
      UsePublishTests:

jobs:
  # Get all the pull requests that are going to main
  Get_Pull_Requests:
    outputs:
      pull_request_ids: ${{ steps.get_pull_requests.outputs.pull_request_ids }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Common
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common
          ref: ${{ inputs.common-ci-ref }}

      # Get all the pull requests into main, and output the ids
      - name: Get Pull Requests
        id: get_pull_requests
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        env:
          PULL_REQUEST_IDS: ${{ inputs.prs }}
        run: |
          . ${{ github.workspace }}/common/nightly-pr-to-main_get-prs.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -VariableName PullRequestIds `
          -GitHubToken ${{ secrets.token }} `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -GitHubOutput $Env:GITHUB_OUTPUT 

  # Run the common workflow on each pull request
  Nightly_PR_to_Main:
    needs: Get_Pull_Requests
    name: Nightly PR to Main - ${{ matrix.id }}
    strategy:
      fail-fast: false
      matrix:
        id: ${{ fromJSON(needs.Get_Pull_Requests.outputs.pull_request_ids) }}

    uses: ./.github/workflows/nightly-pr-to-main.yml
    with:
      repo-name: ${{ inputs.repo-name }}
      org-name: ${{ inputs.org-name }}
      pull-request-id: ${{ matrix.id }}
      user: ${{ inputs.user }}
      email: ${{ inputs.email }}
      dryrun: ${{ inputs.dryrun }}
      cache-assets: ${{ inputs.cache-assets }}
      common-ci-ref: ${{ inputs.common-ci-ref }}
    secrets: inherit
