name: Nightly PR to Main

on:
  workflow_call:
    inputs:
        repo-name:
          required: true
          type: string
        pull-request-id:
          required: true
          type: number
    secrets:
      token:
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.token }}

jobs:
  Configure:
    runs-on: ubuntu-latest
    outputs:
      options: ${{ steps.get_options.outputs.options }}
    steps:
    
      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          ref: gh-refact
          path: common
        
      - name: Configure Git
        run: |
          git config --global url.https://${{ secrets.token }}@github.com/.insteadOf https://github.com/
          git config --global user.email "CI@51Degrees.com"
          git config --global user.name "51DCI"
          
      - name: Clone Repo
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/constants.ps1
          . ${{ github.workspace }}/common/steps/clone-repo.ps1 -RepoName ${{ inputs.repo-name }}
          
      - name: Checkout Pull Request
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/checkout-pr.ps1 -RepoName ${{ inputs.repo-name }} -PullRequestId ${{ inputs.pull-request-id }}
          
      - name: Get Build Options
        id: get_options
        if: ${{ success() }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $OptionsFile = [IO.Path]::Combine($pwd, "${{ inputs.repo-name }}", "ci", "options.json")
          $Options = Get-Content $OptionsFile -Raw
          $Options = $Options -replace "`r`n", "" -replace "`n", ""
          Write-Host $Options
          echo options=$Options | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          
  Build-and-Test:
    needs: Configure
    strategy:
      matrix:
        options: ${{ fromJSON(needs.configure.outputs.options ) }}
    name: Build and Test - ${{ matrix.options.name }}
    runs-on: ${{ matrix.options.image }}
    
    steps:

      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          ref: gh-refact
          path: common

      - name: Configure Git
        run: |
          git config --global url.https://${{ secrets.token }}@github.com/.insteadOf https://github.com/
          git config --global user.email "CI@51Degrees.com"
          git config --global user.name "51DCI"
          
      - name: Clone Repo
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/constants.ps1
          . ${{ github.workspace }}/common/steps/clone-repo.ps1 -RepoName ${{ inputs.repo-name }}
          
      - name: Checkout Pull Request
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/checkout-pr.ps1 -RepoName ${{ inputs.repo-name }} -PullRequestId ${{ inputs.pull-request-id }}
          
      - name: Fetch Assets
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "fetch-assets.ps1"
          
      - name: Setup Environment
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "setup-environment.ps1" -Options $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
            
      - name: Build Project
        id: build
        if: ${{ success() }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          Write-Output ${{ matrix.options }}
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "build-project.ps1" -Options $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          
      - name: Run Unit Tests
        if: ${{ steps.build.conclusion == 'success' }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "run-unit-tests.ps1" -Options $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          
      - name: Run Integration Tests
        if: ${{ steps.build.conclusion == 'success' }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "run-integration-tests.ps1" -Options $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          
      - name: Run Performance Tests
        if: ${{ steps.build.conclusion == 'success' }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/run-repo-script.ps1 -RepoName ${{ inputs.repo-name }} -ScriptName "run-performance-tests.ps1" -Options $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')

      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ steps.build.conclusion == 'success' }}
        with:
          check_name: Unit Tests - ${{ matrix.options.name }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.json
            
      - name: Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ steps.build.conclusion == 'success' }}
        with:
          check_name: Integration Tests - ${{ matrix.options.name }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.json
            
      - name: Performance Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ steps.build.conclusion == 'success' }}
        with:
          check_name: Performance Tests - ${{ matrix.options.name }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.json
            
  Complete:      
    runs-on: ubuntu-latest
    needs: Build-and-Test
    steps:

      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          ref: gh-refact
          path: common

      - name: Configure Git
        run: |
          git config --global url.https://${{ secrets.token }}@github.com/.insteadOf https://github.com/
          git config --global user.email "CI@51Degrees.com"
          git config --global user.name "51DCI"
          
      - name: Clone Repo
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/constants.ps1
          . ${{ github.workspace }}/common/steps/clone-repo.ps1 -RepoName ${{ inputs.repo-name }}
          
      - name: Merge Pull Request
        if: ${{ success() }}
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/merge-pr.ps1 -RepoName ${{ inputs.repo-name }} -PullRequestId ${{ inputs.pull-request-id }}
