name: Nightly PR to Main

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      pull-request-id:
        required: true
        type: number
      org-name:
        required: false
        type: string
        default: 51degrees
      user:
        required: false
        type: string
        default: Automation51D
      email:
        required: false
        type: string
        default: "51DCI@51Degrees.com"
      dryrun:
        required: false
        type: string
        default: false
    secrets:
      token:
        required: true
      asset-keys:
        required: false

jobs:
  Configure:
    name : Configure - ${{ inputs.pull-request-id }} 
    runs-on: ubuntu-latest
    outputs:
      options: ${{ steps.configure.outputs.options }}
    steps:
    
      - name: Checkout Common
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common

      - name: Download Performance Artifact
        uses: actions/download-artifact@v2.1.1
        continue-on-error: true
        with:
          name: performance_results_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common

      - name: Configure
        shell: pwsh
        id: configure
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/nightly-pr-to-main_configure-pr.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }}

  Build-and-Test:
    needs: Configure
    strategy:
      matrix:
        options: ${{ fromJSON(needs.configure.outputs.options ) }}
    name: Build and Test - ${{ inputs.pull-request-id }} - ${{ matrix.options.name }}
    runs-on: ${{ matrix.options.image }}
    
    steps:

      - name: Checkout Common
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common

      - name: Build and Test
        id: build-and-test
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $DryRun = [bool]::Parse( ${{ inputs.dryrun }} )
          $Options = $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          $Options.Add("Keys", $(ConvertFrom-Json -AsHashtable '${{ secrets.asset-keys }}'))
          . ${{ github.workspace }}/common/nightly-pr-to-main_build-and-test.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -Options $Options `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -DryRun $DryRun

      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() }}
        with:
          check_name: Unit Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.json
            
      - name: Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() }}
        with:
          check_name: Integration Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.json
            
      - name: Performance Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() && matrix.options.runperformance }}
        with:
          check_name: Performance Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.json
            
      - name: Upload Performance Results Artifact
        uses: actions/upload-artifact@v3.1.2
        if: ${{ matrix.options.runperformance }}
        with:
          name: performance_results_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance-summary/results_*.json
          if-no-files-found: ignore
                
  Compare-Performance:
    # This needs to run on Windows to support ScottPlot
    runs-on: windows-latest
    needs: [ Configure, Build-and-Test ]
    name: Compare Performance - ${{ inputs.pull-request-id }} 
    steps:
      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common

      - name: Compare Performance
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $DryRun = [bool]::Parse( ${{ inputs.dryrun }} )
          $Options = $(ConvertFrom-Json -AsHashtable '${{ needs.configure.outputs.options }}')
          . ${{ github.workspace }}/common/nightly-pr-to-main_compare-performance.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -Options $Options `
          -RunId ${{ github.run_id }} `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -DryRun $DryRun

      - name: Upload Successful Performance Results Artifact
        if: ${{ success() && matrix.options.runperformance }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: performance_results_passed_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common/results_*.json
          if-no-files-found: ignore

  Complete:      
    runs-on: ubuntu-latest
    name: Complete ${{ inputs.pull-request-id }} 
    needs: [ Build-and-Test, Compare-Performance ]
    steps:

      - name: Checkout Common
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common

      - name: Compete
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $DryRun = [bool]::Parse( ${{ inputs.dryrun }} )
          . ${{ github.workspace }}/common/nightly-pr-to-main_complete.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubToken ${{ secrets.token }} `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -DryRun $DryRun
