name: Nightly PR to Main

on:
  workflow_call:
    inputs:
        repo-name:
          required: true
          type: string
        pull-request-id:
          required: true
          type: number
    secrets:
      token:
        required: true
      asset-keys:
        required: false

jobs:
  Configure:
    runs-on: ubuntu-latest
    outputs:
      options: ${{ steps.configure.outputs.options }}
      options-performance: ${{ steps.configure.outputs.options-performance }}
    steps:
    
      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          path: common

      - name: Configure
        shell: pwsh
        id: configure
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/nightly-pr-to-main_configure-pr.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }}

  Build-and-Test:
    needs: Configure
    strategy:
      matrix:
        options: ${{ fromJSON(needs.configure.outputs.options ) }}
    name: Build and Test - ${{ matrix.options.name }}
    runs-on: ${{ matrix.options.image }}
    
    steps:

      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          path: common

      - name: Build and Test
        id: build-and-test
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $Options = $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          $Options.Add("Keys", $(ConvertFrom-Json -AsHashtable '${{ secrets.asset-keys }}'))
          . ${{ github.workspace }}/common/nightly-pr-to-main_build-and-test.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -Options $Options

      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() }}
        with:
          check_name: Unit Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/unit/**/*.json
            
      - name: Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() }}
        with:
          check_name: Integration Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/integration/**/*.json
            
      - name: Performance Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() && matrix.options.runperformance }}
        with:
          check_name: Performance Tests - ${{ matrix.options.name }}
          commit: ${{ steps.build-and-test.outputs.pr-sha }}
          files: |
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.trx
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.xml
            ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance/**/*.json
            
      - name: Upload Performance Results Artifact
        uses: actions/upload-artifact@v3.1.2
        if: ${{ matrix.options.runperformance }}
        with:
          name: performance_results_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common/${{ inputs.repo-name }}/test-results/performance-summary/results_*.json
          if-no-files-found: ignore
                
  Compare-Performance:
    # This needs to run on Windows to support ScottPlot
    runs-on: windows-latest
    needs: [ Configure, Build-and-Test ]
    strategy:
      # Allow only one at a time so there are no conflicts when committing images
      max-parallel: 1
      matrix:
        options: ${{ fromJSON(needs.configure.outputs.options-performance ) }}
    name: Compare Performance - ${{ matrix.options.name }}
    steps:
      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          path: common

      - name: Download Performance Artifact
        if: ${{ success() && matrix.options.runperformance }}
        uses: actions/download-artifact@v2.1.1
        with:
          name: performance_results_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common

      - name: Compare Performance
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $Options = $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          . ${{ github.workspace }}/common/nightly-pr-to-main_compare-performance.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -GitHubToken ${{ secrets.token }} `
          -GitHubOutput $Env:GITHUB_OUTPUT `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -Options $Options `
          -RunId ${{ github.run_id }}

      - name: Upload Successful Performance Results Artifact
        if: ${{ success() && matrix.options.runperformance }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: performance_results_passed_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common/results_${{ matrix.options.name }}.json
          if-no-files-found: ignore

  Complete:      
    runs-on: ubuntu-latest
    needs: [ Build-and-Test, Compare-Performance ]
    steps:

      - name: Checkout Common
        uses: actions/checkout@v2
        with:
          repository: 51degrees/common-ci
          path: common

      - name: Compete
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $Options = $(ConvertFrom-Json -AsHashtable '${{ toJSON(matrix.options) }}')
          . ${{ github.workspace }}/common/nightly-pr-to-main_complete.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -GitHubToken ${{ secrets.token }} `
          -PullRequestId ${{ inputs.pull-request-id }}
