# This script will automatically synchronize the labels defined in the labels.yml file in this repository
# to all other repositories.
# Note that labels that are removed or renamed in label.yml will be deleted from all repositories.
# Issues and PRs that are tagged with that label will have the label removed.
name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
              51Degrees/caching-dotnet
              51Degrees/cloud-issues
              51Degrees/common-ci
              51Degrees/common-cxx
              51Degrees/data-file-tool
              51Degrees/device-detection-cxx
              51Degrees/device-detection-data
              51Degrees/device-detection-dotnet
              51Degrees/device-detection-go
              51Degrees/device-detection-examples-go
              51Degrees/device-detection-java
              51Degrees/device-detection-nginx
              51Degrees/device-detection-node
              51Degrees/device-detection-php
              51Degrees/device-detection-php-onpremise
              51Degrees/device-detection-python
              51Degrees/device-detection-varnish
              51Degrees/location-dotnet
              51Degrees/location-java
              51Degrees/location-node
              51Degrees/location-php
              51Degrees/location-python
              51Degrees/pipeline-dotnet
              51Degrees/pipeline-java
              51Degrees/pipeline-node
              51Degrees/pipeline-php-cloudrequestengine
              51Degrees/pipeline-php-core
              51Degrees/pipeline-php-engines
              51Degrees/pipeline-python
              51Degrees/pipeline-specification
              51Degrees/Renderer
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
